# flake8: noqa
"""Add the Auth

Revision ID: 140c0dfb2b38
Revises: 81cdde57109b
Create Date: 2025-11-04 01:56:35.419886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140c0dfb2b38'
down_revision: Union[str, Sequence[str], None] = '81cdde57109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyrotechnicians', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyrotechnicians', 'password_hash')
    # ### end Alembic commands ###