# flake8: noqa
"""Change task enums to strings

Revision ID: 145362549c88
Revises: 6c97faff381c
Create Date: 2025-11-03 16:55:57.542172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '145362549c88'
down_revision: Union[str, Sequence[str], None] = '6c97faff381c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               type_=sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority', native_enum=False),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus', native_enum=False),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###