# flake8: noqa
"""Fix onupdate trigger for tasks

Revision ID: 2b7f1436d3a2
Revises: b6ec36673f59
Create Date: 2025-11-03 17:41:20.712807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7f1436d3a2'
down_revision: Union[str, Sequence[str], None] = 'b6ec36673f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###