# flake8: noqa
"""add last_login_at and login_count to pyrotechnicians

Revision ID: 3e8a86b7710f
Revises: b51f79b3a06f
Create Date: 2025-11-10 16:18:28.998582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8a86b7710f'
down_revision: Union[str, Sequence[str], None] = 'b51f79b3a06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyrotechnicians', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pyrotechnicians', sa.Column('login_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_pyrotechnicians_last_login_at'), 'pyrotechnicians', ['last_login_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pyrotechnicians_last_login_at'), table_name='pyrotechnicians')
    op.drop_column('pyrotechnicians', 'login_count')
    op.drop_column('pyrotechnicians', 'last_login_at')
    # ### end Alembic commands ###