# flake8: noqa
"""add is_active_is_admin_to_pyrotechnicians

Revision ID: 45a3c399f455
Revises: ab9bc1082a0b
Create Date: 2025-11-10 12:09:33.502143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a3c399f455'
down_revision: Union[str, Sequence[str], None] = 'ab9bc1082a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyrotechnicians', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('pyrotechnicians', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyrotechnicians', 'is_admin')
    op.drop_column('pyrotechnicians', 'is_active')
    # ### end Alembic commands ###