# flake8: noqa
"""add must_change_password to pyrotechnicians

Revision ID: 661428aa3a33
Revises: 3e8a86b7710f
Create Date: 2025-11-10 17:16:48.983226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661428aa3a33'
down_revision: Union[str, Sequence[str], None] = '3e8a86b7710f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyrotechnicians', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyrotechnicians', 'must_change_password')
    # ### end Alembic commands ###