# flake8: noqa
"""remove vectors add dify_id

Revision ID: 8104c74c2eee
Revises: e39f6b46ebb9
Create Date: 2025-12-12 20:34:33.928684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8104c74c2eee'
down_revision: Union[str, Sequence[str], None] = 'e39f6b46ebb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('dify_document_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_dify_document_id'), 'documents', ['dify_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_dify_document_id'), table_name='documents')
    op.drop_column('documents', 'dify_document_id')
    # ### end Alembic commands ###