# flake8: noqa
"""Add new

Revision ID: ab05a4adbf5d
Revises: 140c0dfb2b38
Create Date: 2025-11-05 12:19:18.711762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab05a4adbf5d'
down_revision: Union[str, Sequence[str], None] = '140c0dfb2b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###