# flake8: noqa
"""add indexes and fk ondelete

Revision ID: ab9bc1082a0b
Revises: ab05a4adbf5d
Create Date: 2025-11-09 21:53:07.928292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab9bc1082a0b"
down_revision: Union[str, Sequence[str], None] = "ab05a4adbf5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # СНАЧАЛА ЧИНИМ ДАННЫЕ:
    # Заполняем NULL-значения email у существующих пиротехников
    # техническими уникальными адресами, чтобы можно было
    # безопасно сделать колонку NOT NULL + UNIQUE.
    op.execute(
        "UPDATE pyrotechnicians "
        "SET email = 'no-email-' || id || '@local' "
        "WHERE email IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("notifications_user_id_fkey"),
        "notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "notifications",
        "pyrotechnicians",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("uq_unit_parent_name"),
        "organization_units",
        type_="unique",
    )
    op.drop_constraint(
        op.f("organization_units_parent_id_fkey"),
        "organization_units",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "organization_units",
        "organization_units",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f(
            "pyrotechnician_team_association_pyrotechnician_id_fkey"
        ),
        "pyrotechnician_team_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("pyrotechnician_team_association_team_id_fkey"),
        "pyrotechnician_team_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "pyrotechnician_team_association",
        "pyrotechnicians",
        ["pyrotechnician_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "pyrotechnician_team_association",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "pyrotechnicians",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.create_index(
        op.f("ix_pyrotechnicians_email"),
        "pyrotechnicians",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_task_attachments_comment_id"),
        "task_attachments",
        ["comment_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("task_attachments_comment_id_fkey"),
        "task_attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "task_attachments",
        "task_comments",
        ["comment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_task_comments_author_id"),
        "task_comments",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_comments_task_id"),
        "task_comments",
        ["task_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("task_comments_task_id_fkey"),
        "task_comments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("task_comments_author_id_fkey"),
        "task_comments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "task_comments",
        "pyrotechnicians",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "task_comments",
        "tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_tasks_priority"),
        "tasks",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_status"),
        "tasks",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_team_id"),
        "tasks",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_zone_id"),
        "tasks",
        ["zone_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("tasks_team_id_fkey"),
        "tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("tasks_zone_id_fkey"),
        "tasks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "tasks",
        "zones",
        ["zone_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "tasks",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_teams_lead_id"),
        "teams",
        ["lead_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("teams_lead_id_fkey"),
        "teams",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("teams_organization_unit_id_fkey"),
        "teams",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "teams",
        "pyrotechnicians",
        ["lead_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "teams",
        "organization_units",
        ["organization_unit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key(
        op.f("teams_organization_unit_id_fkey"),
        "teams",
        "organization_units",
        ["organization_unit_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("teams_lead_id_fkey"),
        "teams",
        "pyrotechnicians",
        ["lead_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_teams_lead_id"), table_name="teams")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_zone_id_fkey"),
        "tasks",
        "zones",
        ["zone_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("tasks_team_id_fkey"),
        "tasks",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_tasks_zone_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_team_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_constraint(None, "task_comments", type_="foreignkey")
    op.drop_constraint(None, "task_comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("task_comments_author_id_fkey"),
        "task_comments",
        "pyrotechnicians",
        ["author_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("task_comments_task_id_fkey"),
        "task_comments",
        "tasks",
        ["task_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_task_comments_task_id"), table_name="task_comments")
    op.drop_index(op.f("ix_task_comments_author_id"), table_name="task_comments")
    op.drop_constraint(None, "task_attachments", type_="foreignkey")
    op.create_foreign_key(
        op.f("task_attachments_comment_id_fkey"),
        "task_attachments",
        "task_comments",
        ["comment_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_task_attachments_comment_id"),
        table_name="task_attachments",
    )
    op.drop_index(
        op.f("ix_pyrotechnicians_email"),
        table_name="pyrotechnicians",
    )
    op.alter_column(
        "pyrotechnicians",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_constraint(
        None, "pyrotechnician_team_association", type_="foreignkey"
    )
    op.drop_constraint(
        None, "pyrotechnician_team_association", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("pyrotechnician_team_association_team_id_fkey"),
        "pyrotechnician_team_association",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("pyrotechnician_team_association_pyrotechnician_id_fkey"),
        "pyrotechnician_team_association",
        "pyrotechnicians",
        ["pyrotechnician_id"],
        ["id"],
    )
    op.drop_constraint(None, "organization_units", type_="foreignkey")
    op.create_foreign_key(
        op.f("organization_units_parent_id_fkey"),
        "organization_units",
        "organization_units",
        ["parent_id"],
        ["id"],
    )
    op.create_unique_constraint(
        op.f("uq_unit_parent_name"),
        "organization_units",
        ["parent_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("notifications_user_id_fkey"),
        "notifications",
        "pyrotechnicians",
        ["user_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_notifications_user_id"),
        table_name="notifications",
    )
    # ### end Alembic commands ###
