# flake8: noqa
"""Add task attachments table

Revision ID: b1757eb92bef
Revises: cf01319efa1a
Create Date: 2025-11-03 18:41:26.741218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1757eb92bef'
down_revision: Union[str, Sequence[str], None] = 'cf01319efa1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('unique_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['task_comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_name')
    )
    op.create_index(op.f('ix_task_attachments_id'), 'task_attachments', ['id'], unique=False)
    op.alter_column('task_comments', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('task_comments_task_id_fkey'), 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.create_foreign_key(op.f('task_comments_task_id_fkey'), 'task_comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_comments', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_task_attachments_id'), table_name='task_attachments')
    op.drop_table('task_attachments')
    # ### end Alembic commands ###