# flake8: noqa
"""add audit and login events

Revision ID: b40a01b9767f
Revises: 45a3c399f455
Create Date: 2025-11-10 14:10:04.262135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40a01b9767f'
down_revision: Union[str, Sequence[str], None] = '45a3c399f455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pyrotechnicians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_type'), 'audit_logs', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pyrotechnicians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_events_created_at'), 'login_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_events_email'), 'login_events', ['email'], unique=False)
    op.create_index(op.f('ix_login_events_id'), 'login_events', ['id'], unique=False)
    op.create_index(op.f('ix_login_events_user_id'), 'login_events', ['user_id'], unique=False)
    op.add_column('pyrotechnicians', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_pyrotechnicians_is_active'), 'pyrotechnicians', ['is_active'], unique=False)
    op.create_index(op.f('ix_pyrotechnicians_is_admin'), 'pyrotechnicians', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pyrotechnicians_is_admin'), table_name='pyrotechnicians')
    op.drop_index(op.f('ix_pyrotechnicians_is_active'), table_name='pyrotechnicians')
    op.drop_column('pyrotechnicians', 'token_version')
    op.drop_index(op.f('ix_login_events_user_id'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_id'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_email'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_created_at'), table_name='login_events')
    op.drop_table('login_events')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###