# flake8: noqa
"""add audit log, login events and token version

Revision ID: b51f79b3a06f
Revises: b40a01b9767f
Create Date: 2025-11-10 15:50:49.676053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51f79b3a06f'
down_revision: Union[str, Sequence[str], None] = 'b40a01b9767f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_login_events_success'), 'login_events', ['success'], unique=False)
    op.create_index('ix_login_events_user_id_created_at', 'login_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_events_user_id_created_at', table_name='login_events')
    op.drop_index(op.f('ix_login_events_success'), table_name='login_events')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    # ### end Alembic commands ###