# flake8: noqa
"""Use plain string for task status and priority

Revision ID: b6ec36673f59
Revises: 145362549c88
Create Date: 2025-11-03 17:04:40.436626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ec36673f59'
down_revision: Union[str, Sequence[str], None] = '145362549c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###