# flake8: noqa
"""Add task comments table

Revision ID: cf01319efa1a
Revises: 2b7f1436d3a2
Create Date: 2025-11-03 18:04:44.911263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf01319efa1a'
down_revision: Union[str, Sequence[str], None] = '2b7f1436d3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###