name: Image Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write  # нужно для пуша в GHCR

jobs:
  # --- БЭКЕНД ---
  scan-backend-image:
    name: Scan Backend Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Compute lowercase owner
        id: repo
        shell: bash
        run: |
          owner="${{ github.repository_owner }}"
          echo "owner_lc=${owner,,}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.owner_lc }}/pyro-api:ci-scan

      - name: Run Trivy scan (backend)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ steps.repo.outputs.owner_lc }}/pyro-api:ci-scan
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH
          exit-code: '1'
          ignore-unfixed: true

  # --- ФРОНТЕНД ---
  scan-frontend-image:
    name: Scan Frontend Docker Image with Trivy
    runs-on: ubuntu-latest
    needs: scan-backend-image

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Compute lowercase owner
        id: repo
        shell: bash
        run: |
          owner="${{ github.repository_owner }}"
          echo "owner_lc=${owner,,}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.owner_lc }}/pyro-frontend:ci-scan

      - name: Run Trivy scan (frontend)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ steps.repo.outputs.owner_lc }}/pyro-frontend:ci-scan
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH
          exit-code: '1'
          ignore-unfixed: true
